# ============================================================
# PSW Portfolio - Image Scanner & Generator
# ============================================================
# USAGE: Right-click -> "Run with PowerShell"
#
# Scans images/home/ and images/work/ then creates
# images/gallery-local.js which the website auto-loads.
# ============================================================

$scriptPath = Split-Path -Parent $MyInvocation.MyCommand.Path
$homeFolder = Join-Path $scriptPath "images\home"
$workFolder = Join-Path $scriptPath "images\work"
$outputFile = Join-Path $scriptPath "images\gallery-local.js"

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  PSW Portfolio - Image Scanner" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# ---- Scan folder ----
function Scan-Folder($folder) {
    if (-not (Test-Path $folder)) { return @() }
    $extensions = @('*.jpg', '*.jpeg', '*.png', '*.webp', '*.avif', '*.gif')
    $images = @()
    foreach ($ext in $extensions) {
        $files = Get-ChildItem -Path $folder -Filter $ext -File | Sort-Object Name
        foreach ($file in $files) { $images += $file }
    }
    return $images
}

Write-Host "Scanning images/home/ ..." -ForegroundColor Yellow
$homeImages = Scan-Folder $homeFolder
Write-Host "  Found $($homeImages.Count) image(s)" -ForegroundColor Green

Write-Host "Scanning images/work/ ..." -ForegroundColor Yellow
$workImages = Scan-Folder $workFolder
Write-Host "  Found $($workImages.Count) image(s)" -ForegroundColor Green
Write-Host ""

if ($homeImages.Count -eq 0 -and $workImages.Count -eq 0) {
    Write-Host "No images found. Drop images into images/home/ or images/work/" -ForegroundColor Red
    Write-Host "then run this script again." -ForegroundColor Red
    pause
    exit
}

# ---- Build JS entries ----
$homeEntries = @()
for ($i = 0; $i -lt $homeImages.Count; $i++) {
    $label = ($i + 1).ToString().PadLeft(2, '0')
    $homeEntries += "    { src: 'images/home/$($homeImages[$i].Name)', label: '$label' }"
}

$workEntries = @()
for ($i = 0; $i -lt $workImages.Count; $i++) {
    $label = ($i + 1).ToString().PadLeft(2, '0')
    $workEntries += "    { src: 'images/work/$($workImages[$i].Name)', label: '$label' }"
}

# ---- Write JS file ----
$lines = @(
    "// AUTO-GENERATED by generate.ps1 - re-run after adding images",
    "// Remove this file to use CDN fallback gallery",
    "const LOCAL_IMAGES = {",
    "  home: ["
)
if ($homeEntries.Count -gt 0) {
    $lines += ($homeEntries -join ",`r`n")
} else {
    $lines += "    // No images in images/home/"
}
$lines += "  ],"
$lines += "  work: ["
if ($workEntries.Count -gt 0) {
    $lines += ($workEntries -join ",`r`n")
} else {
    $lines += "    // No images in images/work/"
}
$lines += "  ]"
$lines += "};"

$content = $lines -join "`r`n"
Set-Content -Path $outputFile -Value $content -Encoding UTF8

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  DONE!" -ForegroundColor Green
Write-Host "  Created: images\gallery-local.js" -ForegroundColor Green
Write-Host "  Home images: $($homeImages.Count)" -ForegroundColor Green
Write-Host "  Work images: $($workImages.Count)" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "The website will now show your local images." -ForegroundColor Green
Write-Host "Refresh the page to see the changes." -ForegroundColor Green
Write-Host ""
pause
